---
- name: "docker"
  path: "/Applications/Docker.app"

- name: "jetbrains-toolbox"
  path: "/Applications/JetBrains Toolbox.app"

- name: "zed"
  path: "/Applications/Zed.app"

- name: "alacritty"
  path: "/Applications/Alacritty.app"
