---
directories:
  - "~/.config"
  - "~/.config/zed"
  - "~/.config/alacritty"
  - "~/.config/opencode/"
  - "~/.config/ghostty/"
  - "~/.config/ghostty/themes/"

symlinks:
  - original: "./files/zshrc_extension"
    destination: "~/.dotfilesrc"

  - original: "./files/gitignore_global"
    destination: "~/.gitignore_global"

  - original: "./files/global_ag_ignore"
    destination: "~/.ag_ignore"

  # Nvim config
  - original: "./files/nvim"
    destination: "~/.config/nvim"

  # Solargraph Config
  - original: "./files/solargraph"
    destination: "~/.config/solargraph"

  # Opencode Config
  - original: "./files/opencode/opencode.jsonc"
    destination: "~/.config/opencode/opencode.jsonc"

  # Ghostty Config
  - original: "./files/ghostty"
    destination: "~/.config/ghostty"

  # Alacritty Config
  - original: "./files/alacritty"
    destination: "~/.config/alacritty/"

  # Zellij Config
  - original: "./files/zellij"
    destination: "~/.config/zellij"

  # Ideavim config
  - original: "./files/vim/ideavim"
    destination: "~/.ideavimrc"

  # Zed Config
  - original: "./files/zed/settings.json"
    destination: "~/.config/zed/settings.json"

  - original: "./files/zed/keymap.json"
    destination: "~/.config/zed/keymap.json"
